version: '3.7'
services:
    redis:
        image: "redis:alpine"
        command: ["redis-server", "--appendonly", "yes","--requirepass","khi7iogU^R"]
        ports:
            - "6379:6379"
        expose:
            - "6379"
        volumes:
         - redis-data:/var/lib/redis
         - redis.conf:/usr/local/etc/redis/redis.conf
        environment:
         - REDIS_REPLICATION_MODE=master
        networks:
            mynet:
                ipv4_address: 172.28.1.4
volumes:
    redis.conf:
    redis-data:
networks:
    mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16